version: '3.5'

services:
  database:
    image: postgres
    container_name: MBLABS_DB
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    expose:
      - ${TYPEORM_PORT}
  app:
    image: node:16
    working_dir: /usr/app
    env_file:
      - ./.env
    container_name: MBLABS_API
    restart: unless-stopped
    depends_on:
      - database
    command: bash -c "yarn install && yarn typeorm migration:run -d src/data-source.ts && yarn start:dev"
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./:/usr/app
