name: Execução de testes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # schedule:
  #   cron: "0 0 * * *"

jobs:
  - name: Teste
      runs-on: ubuntu-latest

      steps:
        - name: Teste
          uses: actions/checkout@v2
  - name: Setup Node.js enviroment
    uses: actions/setup-node@v2
    with:
      node-version: 12.x
      yarn: true
  - name: Install dependencies
    runs: yarn install
  
  - name: Setup Plaright
    uses: microsoft/playwright-github-action@v1

  - name: Run tests
    runs: yarn test